# Generated by Django 3.2.4 on 2021-06-18 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='მისამართი')),
                ('work_days', models.CharField(max_length=60, verbose_name='სამუშაო დღეები')),
                ('tel_number', models.CharField(max_length=2, verbose_name='ტელეფონის ნომერი')),
                ('garage_amount', models.SmallIntegerField(verbose_name='ავტოფარეხის რაოდენობა')),
            ],
            options={
                'verbose_name': 'ფილიალები',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=30, verbose_name='მანქანის ტიპი')),
                ('wash_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='გარეცხვის ღირებულება')),
                ('branch', models.ManyToManyField(to='company.Branch', verbose_name='რომელ ფილიალში რეცხავენ მანქანას')),
            ],
            options={
                'verbose_name': 'მანქანის ტიპები',
            },
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveSmallIntegerField(verbose_name='წილი 1 გარეცხილი მანქანიდან')),
                ('profite', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('is_free', models.BooleanField(default=True, verbose_name='თავისუფალია მრეცხავი ?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='რომელ ფილიალში მუშაობს ?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი')),
            ],
            options={
                'verbose_name': 'მრეცხავები',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='შეკვეთის თარიღი')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='დასრულების დრო')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch', verbose_name='ფილიალი')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.cartype', verbose_name='მანქანის ტიპი')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.washer', verbose_name='მრეცხავი')),
            ],
            options={
                'verbose_name': 'შეკვეთები',
            },
        ),
    ]
