# Generated by Django 3.2.4 on 2021-06-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='finish_date',
        ),
        migrations.AddField(
            model_name='order',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='დასრულებულია ? '),
        ),
    ]
