# Generated by Django 3.2.4 on 2021-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210624_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washer',
            name='profite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
