# Generated by Django 3.2.4 on 2021-07-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_washer_profite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_finished',
        ),
    ]
